use std::env;
use std::fs;
use std::path::{Path, PathBuf};

// Embed the vendored pjdfstest shell suite into the binary at compile time so a
// single fstest artifact runs the whole functional suite without dropping the
// .t files to disk (they are piped to `sh -s` at runtime).
fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let tests_dir = root.join("vendor/pjdfstest/tests");
    println!("cargo:rerun-if-changed=vendor/pjdfstest/tests");
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&tests_dir, "", &mut files);
    files.sort();
    let mut out =
        String::from("// generated by build.rs; DO NOT EDIT\n\npub static TEST_FILES: &[(&str, &str)] = &[\n");
    for (rel, abs) in &files {
        let content = fs::read(abs).unwrap_or_else(|e| panic!("cannot read {}: {e}", abs.display()));
        std::str::from_utf8(&content).unwrap_or_else(|e| panic!("{} is not valid UTF-8: {e}", abs.display()));
        out.push_str(&format!("    ({:?}, include_str!({:?})),\n", rel, abs));
    }
    out.push_str("];\n");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("pjdfstest_files.rs"), out).unwrap();
}

fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).expect("cannot read vendored tests dir") {
        let entry = entry.unwrap();
        let path = entry.path();
        let name = entry.file_name().into_string().unwrap();
        let rel = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}/{name}")
        };
        if path.is_dir() {
            collect(&path, &rel, out);
        } else {
            out.push((rel, path));
        }
    }
}
